### ISSUE TITLE
AttributeError: module 'pysc2' has no attribute 'agents'

### ISSUE THREAD

**Issue by woaipichuli** [starcraft2-ai/rl-battle#9]
I have install as requirement.txt. But I still get some errors.

Traceback (most recent call last):
  File "E:/xx/Bicnet/rl-battle-master/train.py", line 1, in <module>
    from Environment import Environment
  File "E:\xx\Bicnet\rl-battle-master\Environment.py", line 5, in <module>
    class BicNetAgent(pysc2.agents.base_agent.BaseAgent):
AttributeError: module 'pysc2' has no attribute 'agents'

Process finished with exit code 1

**Comment by Willian-Zhang** [comment]
Thank you for trying this repo out.
Unfortunately It's not ready yet, and not in plan of active dev in the next 5 days, however it **could** be after that.
